/*
 * SWAMI KARUPPASWAMI THUNNAI
 * 
 * @author VISWESWARAN NAGASIVAM
 */
package mrida_gui;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Kanchana
 */
public class Mrida extends javax.swing.JFrame {

    /**
     * Creates new form Mrida
     */
    public Mrida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scanLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        ScanPanel = new javax.swing.JPanel();
        fullScanPanel = new javax.swing.JPanel();
        fullScanIcon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        quickScanIcon = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        customScanIcon = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        scanFileIcon = new javax.swing.JLabel();
        UpdatePanel = new javax.swing.JPanel();
        SettingPanel = new javax.swing.JPanel();
        AboutPanel = new javax.swing.JPanel();
        India = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ScanFilePanel = new javax.swing.JPanel();
        fileScanningLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scanFilePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        homeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 102, 51));
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        scanLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        scanLabel.setForeground(new java.awt.Color(255, 102, 51));
        scanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-64.png"))); // NOI18N
        scanLabel.setText("Scan");
        scanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-64.png"))); // NOI18N
        jLabel3.setText("Updates");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-settings-64.png"))); // NOI18N
        jLabel4.setText("Settings");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 102, 51));
        aboutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-about-64.png"))); // NOI18N
        aboutLabel.setText("About");
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        mainPanel.add(HomePanel, "card2");

        ScanPanel.setBackground(new java.awt.Color(255, 255, 255));
        ScanPanel.setLayout(new java.awt.GridLayout(2, 2));

        fullScanPanel.setBackground(new java.awt.Color(255, 255, 255));
        fullScanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullScanPanelMouseEntered(evt);
            }
        });

        fullScanIcon.setBackground(new java.awt.Color(255, 255, 255));
        fullScanIcon.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        fullScanIcon.setForeground(new java.awt.Color(0, 51, 153));
        fullScanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-64.png"))); // NOI18N
        fullScanIcon.setText("FULL SCAN");
        fullScanIcon.setOpaque(true);
        fullScanIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullScanIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullScanIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fullScanPanelLayout = new javax.swing.GroupLayout(fullScanPanel);
        fullScanPanel.setLayout(fullScanPanelLayout);
        fullScanPanelLayout.setHorizontalGroup(
            fullScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullScanPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fullScanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        fullScanPanelLayout.setVerticalGroup(
            fullScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullScanPanelLayout.createSequentialGroup()
                .addComponent(fullScanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ScanPanel.add(fullScanPanel);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        quickScanIcon.setBackground(new java.awt.Color(255, 255, 255));
        quickScanIcon.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        quickScanIcon.setForeground(new java.awt.Color(0, 51, 153));
        quickScanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-64.png"))); // NOI18N
        quickScanIcon.setText("QUICK SCAN");
        quickScanIcon.setOpaque(true);
        quickScanIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quickScanIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quickScanIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(quickScanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(quickScanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ScanPanel.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        customScanIcon.setBackground(new java.awt.Color(255, 255, 255));
        customScanIcon.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        customScanIcon.setForeground(new java.awt.Color(0, 51, 153));
        customScanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-symlink-directory-80.png"))); // NOI18N
        customScanIcon.setText("CUSTOM SCAN");
        customScanIcon.setOpaque(true);
        customScanIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customScanIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customScanIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(customScanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(customScanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ScanPanel.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        scanFileIcon.setBackground(new java.awt.Color(255, 255, 255));
        scanFileIcon.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scanFileIcon.setForeground(new java.awt.Color(0, 51, 153));
        scanFileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-symlink-directory-80.png"))); // NOI18N
        scanFileIcon.setText("SCAN FILE");
        scanFileIcon.setOpaque(true);
        scanFileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanFileIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scanFileIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scanFileIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scanFileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(scanFileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ScanPanel.add(jPanel12);

        mainPanel.add(ScanPanel, "card2");

        javax.swing.GroupLayout UpdatePanelLayout = new javax.swing.GroupLayout(UpdatePanel);
        UpdatePanel.setLayout(UpdatePanelLayout);
        UpdatePanelLayout.setHorizontalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        UpdatePanelLayout.setVerticalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        mainPanel.add(UpdatePanel, "card2");

        javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
        SettingPanel.setLayout(SettingPanelLayout);
        SettingPanelLayout.setHorizontalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        SettingPanelLayout.setVerticalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        mainPanel.add(SettingPanel, "card2");

        AboutPanel.setBackground(new java.awt.Color(255, 255, 255));

        India.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        India.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-india-96.png"))); // NOI18N

        jLabel1.setText("Author: Visweswaran N");

        jLabel2.setText("License: GNU -  GPL 2.0");

        jLabel5.setText("Contact: visweswaran.nagasivam98@gmail.com");

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(India)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(0, 473, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(India, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(AboutPanel, "card2");

        ScanFilePanel.setBackground(new java.awt.Color(255, 255, 255));

        fileScanningLabel.setBackground(new java.awt.Color(0, 102, 153));
        fileScanningLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        fileScanningLabel.setForeground(new java.awt.Color(0, 102, 153));
        fileScanningLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hunt-96.png"))); // NOI18N
        fileScanningLabel.setText("SCANNING FILE");

        jLabel7.setText("Path:");

        javax.swing.GroupLayout ScanFilePanelLayout = new javax.swing.GroupLayout(ScanFilePanel);
        ScanFilePanel.setLayout(ScanFilePanelLayout);
        ScanFilePanelLayout.setHorizontalGroup(
            ScanFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileScanningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ScanFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(scanFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        ScanFilePanelLayout.setVerticalGroup(
            ScanFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScanFilePanelLayout.createSequentialGroup()
                .addComponent(fileScanningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ScanFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(scanFilePath))
                .addGap(0, 498, Short.MAX_VALUE))
        );

        mainPanel.add(ScanFilePanel, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(HomePanel);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(AboutPanel);
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void scanLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanLabelMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(ScanPanel);
    }//GEN-LAST:event_scanLabelMouseClicked

    private void fullScanIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScanIconMouseEntered
        // TODO add your handling code here:
        fullScanIcon.setBackground(Color.PINK);
    }//GEN-LAST:event_fullScanIconMouseEntered

    private void fullScanPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScanPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fullScanPanelMouseEntered

    private void fullScanIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScanIconMouseExited
        // TODO add your handling code here:
        fullScanIcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_fullScanIconMouseExited

    private void quickScanIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickScanIconMouseEntered
        // TODO add your handling code here:
        quickScanIcon.setBackground(Color.PINK);
    }//GEN-LAST:event_quickScanIconMouseEntered

    private void quickScanIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickScanIconMouseExited
        // TODO add your handling code here:
        quickScanIcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_quickScanIconMouseExited

    private void customScanIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customScanIconMouseEntered
        // TODO add your handling code here:
        customScanIcon.setBackground(Color.PINK);
    }//GEN-LAST:event_customScanIconMouseEntered

    private void customScanIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customScanIconMouseExited
        // TODO add your handling code here:
        customScanIcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_customScanIconMouseExited

    private void scanFileIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanFileIconMouseEntered
        // TODO add your handling code here:
        scanFileIcon.setBackground(Color.PINK);
    }//GEN-LAST:event_scanFileIconMouseEntered

    private void scanFileIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanFileIconMouseExited
        // TODO add your handling code here:
        scanFileIcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_scanFileIconMouseExited

    private void scanFileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanFileIconMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if(result!=JFileChooser.APPROVE_OPTION) return;
        File file = chooser.getSelectedFile();
        String fileString = file.getPath();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(ScanFilePanel);
        scanFilePath.setText(fileString);
    }//GEN-LAST:event_scanFileIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mrida mrida = new Mrida();
                mrida.setTitle("Mrida Antivirus");
                mrida.setLocationRelativeTo(null);
                mrida.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel India;
    private javax.swing.JPanel ScanFilePanel;
    private javax.swing.JPanel ScanPanel;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JPanel UpdatePanel;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel customScanIcon;
    private javax.swing.JLabel fileScanningLabel;
    private javax.swing.JLabel fullScanIcon;
    private javax.swing.JPanel fullScanPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel quickScanIcon;
    private javax.swing.JLabel scanFileIcon;
    private javax.swing.JLabel scanFilePath;
    private javax.swing.JLabel scanLabel;
    // End of variables declaration//GEN-END:variables
}
